### PR TITLE
Fix #146 - Emit events around lifecycle tasks

### LINKED ISSUE #146: Emit events for success/failure of tasks
Currently failures occur silently unless you add logic to fail-fast in your task object.

### PR DESCRIPTION
**Pull request by erran-r7**
Fix #146.

# Example output

<pre>ecarey ~/r/b/example-cloud (master)> bundle exec convection converge
converge  Stack vpc
update_in_progress  ecarey-test-cloud-1-vpc: (AWS::CloudFormation::Stack/arn:aws:cloudformation:eu-west-1:...:stack/ecarey-test-cloud-1-vpc/...) User Initiated
update_in_progress  TargetVPC: (AWS::EC2::VPC/vpc-deadb33f) 
update_complete  TargetVPC: (AWS::EC2::VPC/vpc-deadb33f) 
update_complete_cleanup_in_progress  ecarey-test-cloud-1-vpc: (AWS::CloudFormation::Stack/arn:aws:cloudformation:eu-west-1:...:stack/ecarey-test-cloud-1-vpc/...) 
update_complete  ecarey-test-cloud-1-vpc: (AWS::CloudFormation::Stack/arn:aws:cloudformation:eu-west-1:...:stack/ecarey-test-cloud-1-vpc/...) 
<b>task_in_progress  Task (after_update) validate-vpc-stack-outputs in progress for stack vpc.
task_complete  Task (after_update) validate-vpc-stack-outputs successfully completed for stack vpc.</b></pre>

### CODE REVIEW

File: lib/convection/control/stack.rb [hunk 1]
```diff
@@ -229,18 +230,16 @@ def apply(&block)
...
-          task.success?
+          run_task(after_task_type, task, &block)
         end
       rescue Aws::Errors::ServiceError => e
         @errors << e
       end
 
       def delete(&block)
-        ## Execute before delete tasks
+        ## execute before delete tasks
```
Comment (erran-r7) [inline lib/convection/control/stack.rb]: Revert this accidental change.

**Comment by bcall-r7** [comment]
Ship it
